In [1]:
import numpy as np

terrain_data = np.load('terrain_data.npy')
terrain_labels = np.load('terrain_data_labels.npy')
nav_data = np.load('nav_data.npy')
nav_labels = np.load('nav_data_labels.npy')
column_metadata = np.load('surface_columns_metadata.npy')


In [2]:
print(column_metadata)
# Images that were defined as "Indefinido" are not included.
print(np.unique(terrain_labels))
print(len(terrain_labels))
print(len(terrain_data))
print(terrain_labels)
print(terrain_data)


['glmc_disimilarity' 'glmc_correlation' 'slope_max' 'slope_min'
 'slope_variance' 'slope_skewness' 'slope_kurtosis' 'depression_max'
 'depression_min' 'depression_variance' 'depression_skewness'
 'depression_kurtosis' 'rise_max' 'rise_min' 'rise_variance'
 'rise_skewness' 'rise_kurtosis']
[1 2 3 4 5 6]
2461
2461
[1 1 1 ... 5 5 6]
[[ 4.01466667e+00  9.27683865e-01  1.13183451e+00 ...  0.00000000e+00
   0.00000000e+00 -3.00000000e+00]
 [ 3.80000000e-01  5.14408932e-01  6.89634860e-01 ...  6.51166846e-02
   2.78447792e+00  7.96182937e+00]
 [ 2.83244444e+00  9.77752120e-01  1.55150425e+00 ...  0.00000000e+00
   0.00000000e+00 -3.00000000e+00]
 ...
 [ 1.90200000e+01  9.52784174e-01  1.00860100e+01 ...  5.50942587e-05
   4.99699950e+01  2.49500040e+03]
 [ 1.42120000e+01  9.76560489e-01  6.54619455e+00 ...  0.00000000e+00
   0.00000000e+00 -3.00000000e+00]
 [ 1.62142222e+01  9.80752159e-01  1.02224646e+01 ...  5.71018513e-01
   8.77764545e+00  8.19697525e+01]]


In [4]:
print(column_metadata)
# Images that were defined as "Indefinido" are not included.
print(np.unique(nav_labels))
print(len(nav_labels))
print(len(nav_data))
print(nav_labels)
print(nav_data)


['glmc_disimilarity' 'glmc_correlation' 'slope_max' 'slope_min'
 'slope_variance' 'slope_skewness' 'slope_kurtosis' 'depression_max'
 'depression_min' 'depression_variance' 'depression_skewness'
 'depression_kurtosis' 'rise_max' 'rise_min' 'rise_variance'
 'rise_skewness' 'rise_kurtosis']
[1 2 3 4]
856
856
[3 2 3 3 2 3 3 3 2 3 3 3 3 2 2 3 1 1 1 2 4 1 1 4 2 1 4 1 1 1 1 1 2 3 3 2 1
 1 3 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 3 4 4 3 1 4 4 4 3 2 4 4 4 3
 3 3 4 3 4 4 3 4 4 4 3 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 3 3 3 3 3 2 3 2 3 3 3
 3 3 2 3 4 3 4 4 4 4 3 3 4 3 3 4 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 3
 3 3 3 4 4 4 3 3 3 2 3 2 1 1 1 4 4 1 1 4 4 4 1 1 4 1 4 4 3 4 2 4 4 4 4 4 4
 4 4 3 3 4 2 4 1 3 1 3 4 3 3 3 3 4 1 1 3 4 4 3 3 3 3 3 1 1 4 3 1 3 2 1 4 4
 3 2 4 3 2 3 3 3 3 1 4 4 4 4 4 4 4 4 3 4 4 3 3 4 3 3 3 3 3 3 3 4 3 3 2 2 2
 3 3 3 3 3 3 3 2 3 3 4 2 2 3 3 3 2 2 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 4
 4 4 4 4 4 4 4 4 3 4 4 3 4 4 4 3 3 2 1 3 2 2 3 4 3 1 3 2 2 4 4 1 3 3 4 3 3
 4 4 2 4 3 4 4 4 

In [4]:
# The surface labels values correspond to this array, e.g., if label value is '1'
# it means is 'Plano'
terrains = ('Indefinido', 'Plano', 'Bordes',
            'Cráter pequeño', 'Cráter profundo', 'Colina', 'Montaña')
# Same here
navs = ('Indefinido', 'Muy poco navegable', 'Poco navegable',
        'Navegable', 'Muy navegable')
