In [8]:
import numpy as np

terrain_data = np.load('terrain_data.npy')
terrain_labels = np.load('terrain_data_labels.npy')
nav_data = np.load('nav_data.npy')
nav_labels = np.load('nav_data_labels.npy')
column_metadata = np.load('surface_columns_metadata.npy')

In [9]:
print(np.unique(terrain_labels, return_counts=True))
terrain_labels = terrain_labels - 1
print(np.unique(terrain_labels, return_counts=True))

(array([1, 2, 3, 4, 5, 6]), array([1765,  270,  224,  124,  502,  338]))
(array([0, 1, 2, 3, 4, 5]), array([1765,  270,  224,  124,  502,  338]))


In [10]:
terrains = ('Plano', 'Bordes',
            'Cráter pequeño', 'Cráter profundo', 'Colina', 'Montaña')

# Plano
# Desmadre
# Colinas/Monta;a
for i in range(len(terrain_labels)):
    val = terrain_labels[i]
    if val in [2, 3]:
        terrain_labels[i] = 1
    elif val in [4, 5]:
        terrain_labels[i] = 2

print(np.unique(terrain_labels, return_counts=True))

(array([0, 1, 2]), array([1765,  618,  840]))


In [11]:
print(np.unique(nav_labels, return_counts=True))
nav_labels = nav_labels - 1
print(np.unique(nav_labels, return_counts=True))

(array([1, 2, 3, 4]), array([175, 186, 338, 421]))
(array([0, 1, 2, 3]), array([175, 186, 338, 421]))


In [12]:
navs = ('Muy poco navegable', 'Poco navegable',
        'Navegable', 'Muy navegable')

# No navegable y si navegable
for i in range(len(nav_labels)):
    val = nav_labels[i]
    if val == 1:
        nav_labels[i] = 0
    elif val in [2, 3]:
        nav_labels[i] = 1

print(np.unique(nav_labels, return_counts=True))

(array([0, 1]), array([361, 759]))


In [13]:
np.save('terrain_data_labels.npy', terrain_labels)
np.save('nav_data_labels.npy', nav_labels)